# Generated by Django 2.1.5 on 2019-02-10 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPaymentsTransaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=65, verbose_name='Amount')),
                ('confirms_needed', models.PositiveSmallIntegerField(verbose_name='Confirms needed')),
                ('qrcode_url', models.URLField(verbose_name='QR Code Url')),
                ('status_url', models.URLField(verbose_name='Status Url')),
                ('timeout', models.DateTimeField(verbose_name='Valid until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CoinPayments Transaction',
                'verbose_name_plural': 'CoinPayments Transactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('LTC', 'Litecoin'), ('BCH', 'Bitcoin Cash'), ('DASH', 'Dash'), ('ETH', 'Ether'), ('NEO', 'NEO'), ('QTUM', 'Qtum'), ('TUSD', 'TrueUSD'), ('WAVES', 'Waves')], max_length=8, verbose_name='Currency')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=65, verbose_name='Amount')),
                ('amount_paid', models.DecimalField(decimal_places=18, max_digits=65, verbose_name='Amount paid')),
                ('status', models.CharField(choices=[('PRPE', 'Provider-related payment pending'), ('PEND', 'Pending'), ('CNCL', 'Cancelled'), ('TOUT', 'Timed out'), ('PAID', 'Paid')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto_payments.CoinPaymentsTransaction', verbose_name='Payment transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
