# Generated by Django 2.1.5 on 2019-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_currency_original',
            field=models.DecimalField(decimal_places=18, default=10, max_digits=65, verbose_name='Currency Original Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='currency_original',
            field=models.CharField(default='USD', max_length=8, verbose_name='Original currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency_paid',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('LTC', 'Litecoin'), ('BCH', 'Bitcoin Cash'), ('DASH', 'Dash'), ('ETH', 'Ether'), ('NEO', 'NEO'), ('QTUM', 'Qtum'), ('TUSD', 'TrueUSD'), ('WAVES', 'Waves')], default='BTC', max_length=8, verbose_name='Payment currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('CNCL', 'Cancelled'), ('TOUT', 'Timed out'), ('PAID', 'Paid')], max_length=4),
        ),
    ]
