# Generated by Django 2.1.5 on 2019-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_payments', '0002_auto_20190210_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_currency_original',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('TOUT', 'Timed out'), ('PAID', 'Paid')], max_length=4),
        ),
    ]
