# Generated by Django 2.1.5 on 2019-03-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_payments', '0003_auto_20190210_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency_paid',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('LTC', 'Litecoin'), ('BCH', 'Bitcoin Cash'), ('DASH', 'Dash'), ('ETH', 'Ether'), ('QTUM', 'Qtum'), ('TUSD', 'TrueUSD'), ('WAVES', 'Waves')], max_length=8, verbose_name='Payment currency'),
        ),
    ]
