# Generated by Django 2.1.5 on 2019-01-29 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(editable=False, max_length=15, verbose_name='Phone Number')),
                ('system', models.BooleanField(default=False, verbose_name='System')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('active', models.BooleanField(default=True, help_text='Banned or not banned.', verbose_name='Active')),
                ('error_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Error Name')),
                ('error_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Error Datetime')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('messages_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sent Messages')),
                ('invites_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Successful Invites')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
