# Generated by Django 2.1.5 on 2019-03-11 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('phone_code_hash', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Code Hash')),
                ('session', models.CharField(blank=True, max_length=500, null=True, verbose_name='Session String')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(blank=True, max_length=30, null=True, verbose_name='API HASH')),
                ('system', models.BooleanField(default=False, verbose_name='System')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('active', models.BooleanField(default=False, help_text='Banned or not banned.', verbose_name='Active')),
                ('error_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Error Name')),
                ('error_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Error Datetime')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('is_used_now', models.BooleanField(default=False, verbose_name='Is Used Now')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
