# Generated by Django 2.1.5 on 2019-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(default=111, max_length=30, verbose_name='API HASH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='api_id',
            field=models.PositiveIntegerField(default=1111, verbose_name='API ID'),
            preserve_default=False,
        ),
    ]
