# Generated by Django 2.1.5 on 2019-03-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0002_telegramaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(blank=True, default='97dfc2f618ce1b0ac317a25c59fa5666', max_length=40, verbose_name='API HASH'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_id',
            field=models.PositiveIntegerField(blank=True, default=682122, verbose_name='API ID'),
        ),
    ]
