# Generated by Django 2.1.5 on 2019-01-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0002_auto_20190129_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
    ]
