# Generated by Django 2.1.5 on 2019-03-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0003_auto_20190312_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(blank=True, default='97dfc2f618ce1b0ac317a25c59fa5666', max_length=40, verbose_name='API HASH'),
        ),
    ]
