# Generated by Django 2.1.5 on 2019-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0003_auto_20190129_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(max_length=30, null=True, verbose_name='API HASH'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_id',
            field=models.PositiveIntegerField(null=True, verbose_name='API ID'),
        ),
    ]
