# Generated by Django 2.1.5 on 2019-01-31 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0004_auto_20190129_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='API HASH'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='api_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='API ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
