# Generated by Django 2.1.5 on 2019-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0005_auto_20190131_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='phone_code_hash',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Code Hash'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='session',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Session String'),
        ),
    ]
