# Generated by Django 2.1.5 on 2019-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0006_auto_20190202_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='phone_code_hash',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Code Hash'),
        ),
    ]
