# Generated by Django 2.1.5 on 2019-02-03 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0007_auto_20190203_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
