# Generated by Django 2.1.5 on 2019-02-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0008_auto_20190203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='is_used_now',
            field=models.BooleanField(default=False, verbose_name='Is Used Now'),
        ),
    ]
