# Generated by Django 2.1.5 on 2019-02-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0009_telegramaccount_is_used_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramaccount',
            name='invites_count',
        ),
        migrations.RemoveField(
            model_name='telegramaccount',
            name='messages_count',
        ),
    ]
