# Generated by Django 2.1.5 on 2019-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('error', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('error', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
