# Generated by Django 2.1.5 on 2019-03-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_accounts', '0001_initial'),
        ('actions', '0001_initial'),
        ('telegram_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_entities.TelegramContact'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_entities.Message'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='telegram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_accounts.TelegramAccount'),
        ),
        migrations.AddField(
            model_name='messageevent',
            name='telegram_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_entities.TelegramGroup'),
        ),
    ]
