# Generated by Django 2.1.5 on 2019-02-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_entities', '0001_initial'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='source_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites_from', to='telegram_entities.TelegramGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='target_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites_to', to='telegram_entities.TelegramGroup'),
            preserve_default=False,
        ),
    ]
