# Generated by Django 2.1.5 on 2019-03-11 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_accounts', '0001_initial'),
        ('actions', '0002_auto_20190311_2044'),
        ('telegram_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inviteevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='telegram_entities.TelegramContact'),
        ),
        migrations.AddField(
            model_name='inviteevent',
            name='source_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_from', to='telegram_entities.TelegramGroup'),
        ),
        migrations.AddField(
            model_name='inviteevent',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_to', to='telegram_entities.TelegramGroup'),
        ),
        migrations.AddField(
            model_name='inviteevent',
            name='telegram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_events', to='telegram_accounts.TelegramAccount'),
        ),
        migrations.AddField(
            model_name='inviteevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
