# Generated by Django 2.1.5 on 2019-02-09 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_entities', '0003_auto_20190209_1420'),
        ('telegram_accounts', '0009_telegramaccount_is_used_now'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_auto_20190203_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('error', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='telegram_entities.TelegramContact')),
                ('source_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_from', to='telegram_entities.TelegramGroup')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_to', to='telegram_entities.TelegramGroup')),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_events', to='telegram_accounts.TelegramAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('error', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_entities.TelegramContact')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_entities.Message')),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_accounts.TelegramAccount')),
                ('telegram_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='telegram_entities.TelegramGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='invite',
            name='source_group',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='target_group',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='telegram_account',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
