# Generated by Django 2.1.5 on 2019-03-13 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20190313_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteevent',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_from', to='telegram_entities.TelegramGroup'),
        ),
        migrations.AlterField(
            model_name='inviteevent',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_to', to='telegram_entities.TelegramGroup'),
        ),
        migrations.AlterField(
            model_name='inviteevent',
            name='telegram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_events', to='telegram_accounts.TelegramAccount'),
        ),
        migrations.AlterField(
            model_name='inviteevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageevent',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_events', to='telegram_entities.Message'),
        ),
        migrations.AlterField(
            model_name='messageevent',
            name='telegram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_events', to='telegram_accounts.TelegramAccount'),
        ),
        migrations.AlterField(
            model_name='messageevent',
            name='telegram_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_events', to='telegram_entities.TelegramGroup'),
        ),
    ]
