# Generated by Django 2.1.5 on 2019-02-03 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('scrapped_count', models.PositiveIntegerField(default=0, verbose_name='Scrapped')),
                ('invited_count', models.PositiveIntegerField(default=0, verbose_name='Scrapped')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
