# Generated by Django 2.1.5 on 2019-03-11 20:44

import apps.telegram_entities.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Message Title')),
                ('text', models.TextField(max_length=4096, verbose_name='Message Text')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.telegram_entities.models.get_file_upload_path, verbose_name='File')),
                ('link_preview', models.BooleanField(default=True, verbose_name='Link Preview')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('priority', models.PositiveIntegerField(blank=True, help_text='Based on contact activity.', null=True, verbose_name='Priority')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Username')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('join_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Join Link')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
