# Generated by Django 2.1.5 on 2019-02-09 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_entities', '0002_auto_20190203_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Message Title')),
                ('text', models.TextField(max_length=4096, verbose_name='Message Text')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('priority', models.PositiveIntegerField(blank=True, help_text='Based on contact activity.', null=True, verbose_name='Priority')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='join_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Join Link'),
        ),
        migrations.AddField(
            model_name='telegramcontact',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_contacts', to='telegram_entities.TelegramGroup'),
        ),
        migrations.AddField(
            model_name='telegramcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
