# Generated by Django 2.1.5 on 2019-02-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_entities', '0003_auto_20190209_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='invited_count',
        ),
        migrations.RemoveField(
            model_name='telegramgroup',
            name='scrapped_count',
        ),
    ]
