# Generated by Django 2.1.5 on 2019-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_entities', '0004_auto_20190209_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='join_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Join Link'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Username'),
        ),
    ]
