# Generated by Django 2.1.5 on 2019-03-02 15:05

import apps.telegram_entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_entities', '0006_auto_20190209_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.telegram_entities.models.get_file_upload_path, verbose_name='File'),
        ),
    ]
