# Generated by Django 2.1.5 on 2019-03-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_entities', '0007_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='test', max_length=200, verbose_name='Message Title'),
            preserve_default=False,
        ),
    ]
