# Generated by Django 2.1.5 on 2019-03-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_entities', '0008_auto_20190302_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_preview',
            field=models.BooleanField(default=True, verbose_name='Link Preview'),
        ),
    ]
